2018-12-15 16:48:53 下午 [Thread: pool-1-thread-3][ Class:task.AbstractThreadTask >> Method: task.AbstractThreadTask.call(AbstractThreadTask.java:141) ]
ERROR:pool-1-thread-3_AbstractThreadTask发生异常,params:null
java.lang.RuntimeException: 测试错误
	at ErrorTaskTest.excute(ErrorTaskTest.java:15)
	at task.AbstractThreadTask.call(AbstractThreadTask.java:136)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-12-15 18:14:20 下午 [Thread: pool-1-thread-3][ Class:task.AbstractThreadTask >> Method: task.AbstractThreadTask.call(AbstractThreadTask.java:141) ]
ERROR:pool-1-thread-3_AbstractThreadTask发生异常,params:null
java.lang.RuntimeException: 测试错误
	at ErrorTaskTest.excute(ErrorTaskTest.java:15)
	at task.AbstractThreadTask.call(AbstractThreadTask.java:136)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-12-15 18:25:12 下午 [Thread: pool-1-thread-3][ Class:task.AbstractThreadTask >> Method: task.AbstractThreadTask.call(AbstractThreadTask.java:151) ]
ERROR:task3发生异常,params:null
java.lang.RuntimeException: 测试错误
	at ErrorTaskTest.excute(ErrorTaskTest.java:15)
	at task.AbstractThreadTask.call(AbstractThreadTask.java:146)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-12-15 18:53:13 下午 [Thread: pool-1-thread-3][ Class:task.AbstractThreadTask >> Method: task.AbstractThreadTask.call(AbstractThreadTask.java:156) ]
ERROR:task3发生异常,params:null
java.lang.RuntimeException: 测试错误
	at ErrorTaskTest.excute(ErrorTaskTest.java:15)
	at task.AbstractThreadTask.call(AbstractThreadTask.java:151)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-12-15 18:54:04 下午 [Thread: pool-1-thread-3][ Class:task.AbstractThreadTask >> Method: task.AbstractThreadTask.call(AbstractThreadTask.java:156) ]
ERROR:main_AbstractThreadTask发生异常,params:null
java.lang.RuntimeException: 测试错误
	at ErrorTaskTest.excute(ErrorTaskTest.java:15)
	at task.AbstractThreadTask.call(AbstractThreadTask.java:151)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-12-15 21:57:16 下午 [Thread: pool-1-thread-3][ Class:task.AbstractThreadTask >> Method: task.AbstractThreadTask.call(AbstractThreadTask.java:154) ]
ERROR:main_AbstractThreadTask发生异常,params:null
java.lang.RuntimeException: 测试错误
	at ErrorTaskTest.excute(ErrorTaskTest.java:15)
	at task.AbstractThreadTask.call(AbstractThreadTask.java:149)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
